### ISSUE TITLE
Breaks with flax > 0.8.0

### ISSUE THREAD

**Issue by unautre** [BobMcDear/open-clip-jax#1]
Hello,

The library fails to import with the following error when flax > 0.8.0 is installed:
```
Error: While importing 'main', an ImportError was raised:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/flask/cli.py", line 245, in locate_app
    __import__(module_name)
  File "/usr/app/main.py", line 6, in <module>
    from open_clip_jax import create_image_transforms, create_model_with_params, tokenize
  File "/usr/local/lib/python3.11/dist-packages/open_clip_jax/__init__.py", line 12, in <module>
    from .clip import (
  File "/usr/local/lib/python3.11/dist-packages/open_clip_jax/clip/__init__.py", line 7, in <module>
    from .factory import (
  File "/usr/local/lib/python3.11/dist-packages/open_clip_jax/clip/factory.py", line 16, in <module>
    from .convnext import ConvNeXt
  File "/usr/local/lib/python3.11/dist-packages/open_clip_jax/clip/convnext.py", line 9, in <module>
    from flax.linen.dtypes import Array, Dtype
ImportError: cannot import name 'Array' from 'flax.linen.dtypes' (/usr/local/lib/python3.11/dist-packages/flax/linen/dtypes.py)
```

This occurs after this commit from the flax team: https://github.com/google/flax/commit/49ba155170dc98a0605f70a8f653d1317bb2e49e#diff-9086fe84a0b2271710d5cbaca6aca9ed346dff7f20449c74a0424b301218bc4f

The version of flax should either be enforced <= 0.8.0, or flax's `Array` should be imported from flax's new `dtypes` module.

**Comment by BobMcDear** [comment]
Hello,

Thank you very much for bringing this issue to my attention. I have now restricted the Flax version to less than or equal to ```0.8.0```.
